### PR TITLE
[Fixes #156] Return response outside of transaction to prevent test failures

### LINKED ISSUE #156: Ringdown `creates a new ambulance record as needed` test is failing
When executing `npm run test:server`, the test ends with this output:

```
  /api/ringdowns
    GET /
      ✓ returns a list of all ringdowns (65ms)
      ✓ returns a list of all ringdowns filtered by hospital (64ms)
      ✓ returns a list of active ringdowns created by the calling EMS user (66ms)
    POST /
      ✓ creates a ringdown (70ms)
      1) "before each" hook for "creates a new ambulance record as needed"


  9 passing (2s)
  1 failing

  1) "before each" hook for "creates a new ambulance record as needed":
     SequelizeForeignKeyConstraintError: update or delete on table "ambulance" violates foreign key constraint "patientdelivery_ambulance_fk" on table "patientdelivery"
      at Query.formatError (node_modules/sequelize/lib/dialects/postgres/query.js:315:16)
      at Query.run (node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /opt/node/app/node_modules/sequelize/lib/sequelize.js:619:16
      at async resetDatabase (test/helper.js:18:3)
      at async Context.<anonymous> (test/helper.js:34:3)
```

The test stops after that, so it's possible there are other failing tests.  I'm not familiar enough with Mocha to know how to force it to keep going.  (From the docs, it seems like it should by default.)

### PR DESCRIPTION
**Pull request by francisli**

### CODE REVIEW

**Comment by francisli** [comment]
@fwextensions does this help the tests pass reliably on your machine?

**Comment by fwextensions** [comment]
The ambulance ringdown POST test now completes, but there's still that test failure I mentioned in #156:

```
  38 passing (8s)
  1 failing

  1) /api/ringdowns
       PATCH /:id
         updates an existing ringdown:
     AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:

null !== 99

      at Context.<anonymous> (test/integration/api/ringdowns.js:369:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by francisli** [comment]
@fwextensions ok, updated the other PATCH routes with the same fix, try again...?

**Comment by fwextensions** [comment]
Okay, the full suite passes now.  Were you not seeing these test failures in your environment?

**Comment by francisli** [comment]
@fwextensions no, I was not able to reproduce test failures for the PATCH routes... the test suite also runs and passes in CircleCI... but glad it was worked out...

**Review by fwextensions — APPROVED** [review]

**Pull request merged**
